### ISSUE TITLE
List all languages collection and spoken languages collection

### ISSUE THREAD

**Issue by hedythedev** [hedythedev/gtrending#4]
The github-trending-api also provides the [languages collection](https://githubtrendingapi.docs.apiary.io/#reference/0/languages-collection) and the [spoken languages collection](https://githubtrendingapi.docs.apiary.io/#reference/0/spoken-languages-collection). 

We could provide functions like `languages_list()` and `spoken_languages_list()` that returns a list of   dicts, like the response from [here](https://githubtrendingapi.docs.apiary.io/#reference/0/languages-collection/list-languages) and [here](https://githubtrendingapi.docs.apiary.io/#reference/0/spoken-languages-collection/list-spoken-languages).

![Screenshot_20200829_081102](https://user-images.githubusercontent.com/50042066/91623739-2db8cb00-e98c-11ea-9dc3-30870747c74d.jpg)
![Screenshot_20200829_081118](https://user-images.githubusercontent.com/50042066/91623742-31e4e880-e98c-11ea-9cad-3afc154017dd.jpg)

**Comment by berrybretch** [comment]
I would like to claim this issue.

**Comment by hedythedev** [comment]
Fixed in #7
