### ISSUE TITLE
Add API reference to docs

### ISSUE THREAD

**Issue by hedythedev** [hedythedev/gtrending#6]
It would be good if the auto documenting reference section for our [read the docs site](https://gtrending.readthedocs.io/en/latest/) can be set up so that whenever new API is added or updated, this section will update on every build.

The docs are in `docs/`

**Comment by fokoid** [comment]
I'm interested in picking this up. I am guessing what's needed is:
1. set up autogeneration of documentation based on docstrings using `sphinx.ext.autodoc`
2. create a GitHub Actions workflow to run the generation and deploy to readthedocs
3. either find a way to auto-update the readme too, or remove API docs from the readme in favor of the readthedocs documentation

I couldn't figure out how much of 1 and 3 is already done. I see docstring based API docs in the readme but couldn't see how it was generated. Please do let me know and then I'll get started.

**Comment by hedythedev** [comment]
thanks for your interest. The API docs in the readme is written by myself, and the use of auto doc generation is a good idea. however I'm not sure if the github workflow is needed as the readthedocs build is done automatically on every push. Let me know if I missed something.

If the API reference in readthedocs is done, I don't think it would be needed in the readme anymore. Could be replaced by some more example usage.

**Comment by fokoid** [comment]
I agree now that 2) is not needed. I assumed the documentation build & deploy ran as a GitHub workflow (and couldn't find any such workflow configured), but having read some more about readthedocs I realized it's done on the readthedocs servers - my mistake.

I will have a go at setting up auto doc generation and let you know how I get on.
